### PR TITLE
Request/response editor

### PR DESCRIPTION
**Pull request by h3xstream**
Make use of createMessageEditor() to use Burp "native" request/response editor

Specialized requests will benefit from custom view in request and response tab.

The change is overriding 95765ee123be51608013730bbb3c4addd30ae9fd

### CODE REVIEW

**Comment by swagnetow** [comment]
Thanks for the pull request, @h3xstream! Merged.

**Comment by jhaddix** [comment]
Any reason why right click functions will not work with the new  "native" request/response editor?

Send to Repeater, ++ does nothing, Running latest Burp version, windows 10.

**Comment by swagnetow** [comment]
@h3xstream I'm experiencing the same thing so I reverted the pull request. Please submit another pull request when you can get the context menu to work properly.

**Comment by h3xstream** [comment]
The context menu is built-in to the request view.

**Comment by h3xstream** [comment]
Nvm .. I just saw that a stack trace appears in the console rather than sending the request to repeater.

**Comment by swagnetow** [comment]
@h3xstream Hey there, I found out what the problem was! In your implementation of StaticMessageController, the function should be called `getHttpService()` and not `getIHttpService()`. I would very much like for you to get credit for contributing so if you could, could you please send another pull request along with the fix that I mentioned? Thanks.

**Pull request merged**
